import type { EditorialCinematicData, PrototypeImage } from "@/prototypes/editorial-cinematic/prototype-data";

const image = (file: string, alt: string, position = "50% 50%"): PrototypeImage => ({
  src: `/images/lab/${["Marina e Thiago", ...file.split("/")].map(encodeURIComponent).join("/")}`,
  alt,
  position,
});

export const marinaEThiago = {
  couple: { partnerOne: "Marina", partnerTwo: "Thiago" },
  date: "04/04/2025",
  location: "Cumbuco-CE",
  photographer: null,
  theme: {
    ivory: "#f2eee4",
    paper: "#e6dfd1",
    charcoal: "#24231f",
    black: "#090a08",
    olive: "#60634e",
    gold: "#b29a68",
  },
  hero: image("Celebração/IMG_0130.webp", "Marina e Thiago no altar à beira-mar, sob as luzes da cerimônia"),
  editorialIntro: {
    eyebrow: "Capítulo I",
    title: "O começo",
    titleLines: ["O", "começo"],
    body: "Algumas histórias chegam de mansinho. Outras parecem fazer parte de nós desde o primeiro instante.",
    caption: "Os primeiros instantes de um novo capítulo",
    primary: image("Preparação/IMG_9460.webp", "Marina com seu buquê durante os preparativos"),
    secondary: image("Preparação/IMG_9232.webp", "Thiago ajustando o traje antes da cerimônia"),
  },
  detailsImages: [
    image("Decoração/IMG_0069.webp", "Mesa de doces e flores com o mar ao fundo"),
    image("Decoração/15.webp", "Bolo de casamento entre flores brancas"),
    image("Decoração/GAB06449.webp", "Placa de boas-vindas ao casamento de Marina e Thiago"),
    image("Decoração/GAB06455.webp", "Mesa posta com taças, pratos e arranjos florais"),
  ],
  ceremonyImages: [
    image("Celebração/IMG_9981.webp", "Marina entrando na cerimônia acompanhada"),
    image("Celebração/IMG_9914.webp", "Convidados reunidos sob as palmeiras para a cerimônia"),
    image("Celebração/IMG_9895.webp", "Thiago aguardando a chegada de Marina"),
    image("Celebração/IMG_0182.webp", "Marina e Thiago de mãos dadas diante do altar"),
    image("Celebração/GAB07176.webp", "Detalhe em preto e branco das mãos dos noivos na cerimônia"),
    image("Beijo/IMG_0590.webp", "O beijo de Marina e Thiago após o sim"),
  ],
  coupleImages: [
    image("Nossos passos/164.webp", "Marina e Thiago abraçados em um retrato noturno", "50% 65%"),
    image("Nossos passos/160.webp", "Os noivos caminhando de mãos dadas à noite", "50% 70%"),
    image("Nossos passos/159.webp", "Marina e Thiago juntos sob a luz na areia", "50% 70%"),
    image("Nossos passos/161.webp", "O casal caminhando com a cauda do vestido sobre a areia", "50% 70%"),
    image("Nossos passos/162.webp", "Marina e Thiago trocando olhares durante a caminhada", "50% 70%"),
  ],
  portraitImages: [
    image("Preparação/IMG_9359.webp", "Marina de costas, com a cauda do vestido sobre o gramado"),
    image("Preparação/IMG_9364.webp", "Retrato de Marina com o buquê no jardim"),
    image("Nossos passos/167.webp", "Detalhe do vestido e dos passos dos noivos na areia"),
    image("Saída/113.webp", "Marina e Thiago saindo da cerimônia entre os convidados"),
    image("Beijo/IMG_0636.webp", "Marina e Thiago se beijando sob as luzes da noite"),
  ],
  celebrationImages: [
    image("Festa/187.webp", "Marina e Thiago juntos na pista de dança"),
    image("Festa/189.webp", "Os noivos abraçados durante a festa"),
    image("Festa/183.webp", "Marina e Thiago celebrando com os braços erguidos"),
    image("Festa/188.webp", "Um beijo dos noivos no meio da celebração"),
    image("Festa/IMG_1797.webp", "Marina comemorando ao lado de uma convidada"),
    image("Festa/IMG_1574.webp", "Convidados e noivos celebrando juntos"),
    image("Festa/186.webp", "Amigos reunidos ao redor do casal na pista"),
  ],
  guests: {
    headline: "Gratidão por quem fez parte desse dia conosco",
    images: [
      { src: "/images/lab/convidados-web/IMG_0752.webp", alt: "Convidados celebrando com Marina e Thiago, fotografia 1", position: "50% 50%" },
      { src: "/images/lab/convidados-web/IMG_0758.webp", alt: "Convidados celebrando com Marina e Thiago, fotografia 2", position: "50% 50%" },
      { src: "/images/lab/convidados-web/IMG_0763.webp", alt: "Convidados celebrando com Marina e Thiago, fotografia 3", position: "50% 50%" },
      { src: "/images/lab/convidados-web/IMG_0787.webp", alt: "Convidados celebrando com Marina e Thiago, fotografia 4", position: "50% 50%" },
      { src: "/images/lab/convidados-web/IMG_0794.webp", alt: "Convidados celebrando com Marina e Thiago, fotografia 5", position: "50% 50%" },
      { src: "/images/lab/convidados-web/IMG_0802.webp", alt: "Convidados celebrando com Marina e Thiago, fotografia 6", position: "50% 50%" },
      { src: "/images/lab/convidados-web/IMG_0816.webp", alt: "Convidados celebrando com Marina e Thiago, fotografia 7", position: "50% 50%" },
      { src: "/images/lab/convidados-web/IMG_0833.webp", alt: "Convidados celebrando com Marina e Thiago, fotografia 8", position: "50% 50%" },
      { src: "/images/lab/convidados-web/IMG_0837.webp", alt: "Convidados celebrando com Marina e Thiago, fotografia 9", position: "50% 50%" },
      { src: "/images/lab/convidados-web/IMG_0853.webp", alt: "Convidados celebrando com Marina e Thiago, fotografia 10", position: "50% 50%" },
      { src: "/images/lab/convidados-web/IMG_0856.webp", alt: "Convidados celebrando com Marina e Thiago, fotografia 11", position: "50% 50%" },
      { src: "/images/lab/convidados-web/IMG_0864.webp", alt: "Convidados celebrando com Marina e Thiago, fotografia 12", position: "50% 50%" },
      { src: "/images/lab/convidados-web/IMG_0884.webp", alt: "Convidados celebrando com Marina e Thiago, fotografia 13", position: "50% 50%" },
      { src: "/images/lab/convidados-web/IMG_0887.webp", alt: "Convidados celebrando com Marina e Thiago, fotografia 14", position: "50% 50%" },
      { src: "/images/lab/convidados-web/IMG_0894.webp", alt: "Convidados celebrando com Marina e Thiago, fotografia 15", position: "50% 50%" },
      { src: "/images/lab/convidados-web/IMG_0921.webp", alt: "Convidados celebrando com Marina e Thiago, fotografia 16", position: "50% 50%" },
      { src: "/images/lab/convidados-web/IMG_0931.webp", alt: "Convidados celebrando com Marina e Thiago, fotografia 17", position: "50% 50%" },
      { src: "/images/lab/convidados-web/IMG_0932.webp", alt: "Convidados celebrando com Marina e Thiago, fotografia 18", position: "50% 50%" },
      { src: "/images/lab/convidados-web/IMG_0938.webp", alt: "Convidados celebrando com Marina e Thiago, fotografia 19", position: "50% 50%" },
      { src: "/images/lab/convidados-web/IMG_0945.webp", alt: "Convidados celebrando com Marina e Thiago, fotografia 20", position: "50% 50%" },
      { src: "/images/lab/convidados-web/IMG_0953.webp", alt: "Convidados celebrando com Marina e Thiago, fotografia 21", position: "50% 50%" },
      { src: "/images/lab/convidados-web/IMG_0962.webp", alt: "Convidados celebrando com Marina e Thiago, fotografia 22", position: "50% 50%" },
      { src: "/images/lab/convidados-web/IMG_0972.webp", alt: "Convidados celebrando com Marina e Thiago, fotografia 23", position: "50% 50%" },
      { src: "/images/lab/convidados-web/IMG_0981.webp", alt: "Convidados celebrando com Marina e Thiago, fotografia 24", position: "50% 50%" },
      { src: "/images/lab/convidados-web/IMG_0988.webp", alt: "Convidados celebrando com Marina e Thiago, fotografia 25", position: "50% 50%" },
      { src: "/images/lab/convidados-web/IMG_1008.webp", alt: "Convidados celebrando com Marina e Thiago, fotografia 26", position: "50% 50%" },
      { src: "/images/lab/convidados-web/IMG_1020.webp", alt: "Convidados celebrando com Marina e Thiago, fotografia 27", position: "50% 50%" },
      { src: "/images/lab/convidados-web/IMG_1041.webp", alt: "Convidados celebrando com Marina e Thiago, fotografia 28", position: "50% 50%" },
      { src: "/images/lab/convidados-web/IMG_1070.webp", alt: "Convidados celebrando com Marina e Thiago, fotografia 29", position: "50% 50%" },
      { src: "/images/lab/convidados-web/IMG_1082.webp", alt: "Convidados celebrando com Marina e Thiago, fotografia 30", position: "50% 50%" },
      { src: "/images/lab/convidados-web/IMG_1093.webp", alt: "Convidados celebrando com Marina e Thiago, fotografia 31", position: "50% 50%" },
      { src: "/images/lab/convidados-web/IMG_1334.webp", alt: "Convidados celebrando com Marina e Thiago, fotografia 32", position: "50% 50%" },
      { src: "/images/lab/convidados-web/IMG_1342.webp", alt: "Convidados celebrando com Marina e Thiago, fotografia 33", position: "50% 50%" },
      { src: "/images/lab/convidados-web/IMG_1353.webp", alt: "Convidados celebrando com Marina e Thiago, fotografia 34", position: "50% 50%" },
      { src: "/images/lab/convidados-web/IMG_1362.webp", alt: "Convidados celebrando com Marina e Thiago, fotografia 35", position: "50% 50%" },
      { src: "/images/lab/convidados-web/IMG_1381.webp", alt: "Convidados celebrando com Marina e Thiago, fotografia 36", position: "50% 50%" },
      { src: "/images/lab/convidados-web/IMG_1387.webp", alt: "Convidados celebrando com Marina e Thiago, fotografia 37", position: "50% 50%" },
      { src: "/images/lab/convidados-web/IMG_1390.webp", alt: "Convidados celebrando com Marina e Thiago, fotografia 38", position: "50% 50%" },
      { src: "/images/lab/convidados-web/IMG_1393.webp", alt: "Convidados celebrando com Marina e Thiago, fotografia 39", position: "50% 50%" },
      { src: "/images/lab/convidados-web/IMG_1405.webp", alt: "Convidados celebrando com Marina e Thiago, fotografia 40", position: "50% 50%" },
      { src: "/images/lab/convidados-web/IMG_1410.webp", alt: "Convidados celebrando com Marina e Thiago, fotografia 41", position: "50% 50%" },
      { src: "/images/lab/convidados-web/IMG_1497.webp", alt: "Convidados celebrando com Marina e Thiago, fotografia 42", position: "50% 50%" },
      { src: "/images/lab/convidados-web/IMG_1507.webp", alt: "Convidados celebrando com Marina e Thiago, fotografia 43", position: "50% 50%" },
      { src: "/images/lab/convidados-web/IMG_1514.webp", alt: "Convidados celebrando com Marina e Thiago, fotografia 44", position: "50% 50%" },
      { src: "/images/lab/convidados-web/IMG_1519.webp", alt: "Convidados celebrando com Marina e Thiago, fotografia 45", position: "50% 50%" },
      { src: "/images/lab/convidados-web/IMG_1524.webp", alt: "Convidados celebrando com Marina e Thiago, fotografia 46", position: "50% 50%" },
      { src: "/images/lab/convidados-web/IMG_1525.webp", alt: "Convidados celebrando com Marina e Thiago, fotografia 47", position: "50% 50%" },
      { src: "/images/lab/convidados-web/IMG_1543.webp", alt: "Convidados celebrando com Marina e Thiago, fotografia 48", position: "50% 50%" },
      { src: "/images/lab/convidados-web/IMG_1549.webp", alt: "Convidados celebrando com Marina e Thiago, fotografia 49", position: "50% 50%" },
      { src: "/images/lab/convidados-web/IMG_1574.webp", alt: "Convidados celebrando com Marina e Thiago, fotografia 50", position: "50% 50%" },
      { src: "/images/lab/convidados-web/IMG_1580.webp", alt: "Convidados celebrando com Marina e Thiago, fotografia 51", position: "50% 50%" },
      { src: "/images/lab/convidados-web/IMG_1598.webp", alt: "Convidados celebrando com Marina e Thiago, fotografia 52", position: "50% 50%" },
      { src: "/images/lab/convidados-web/IMG_1610.webp", alt: "Convidados celebrando com Marina e Thiago, fotografia 53", position: "50% 50%" },
    ],
  },
  guestbook: {
    messages: [
      {
        name: "Padrinhos",
        relationship: "Com amor",
        message: "Que a alegria desta noite acompanhe vocês em todos os dias que virão.",
      },
      {
        name: "Amigos da praia",
        relationship: "Amigos dos noivos",
        message: "Foi lindo celebrar um amor tão leve, cheio de presença e de verdade.",
      },
      {
        name: "Família",
        relationship: "Para Marina e Thiago",
        message: "Que nunca faltem abraço, parceria e motivos para comemorar juntos.",
      },
      {
        name: "Amigos de longa data",
        relationship: "Com carinho",
        message: "Uma noite para guardar no coração. Que a história de vocês siga ainda mais bonita.",
      },
      {
        name: "Quem esteve presente",
        relationship: "Neste dia especial",
        message: "Entre o mar, as luzes e tantos sorrisos, vimos o começo de uma vida inteira.",
      },
      {
        name: "Com muito carinho",
        relationship: "Para o casal",
        message: "Que cada novo capítulo tenha a mesma beleza e alegria deste encontro.",
      },
    ],
  },
  closing: {
    image: image("Saída/IMG_0684.webp", "Marina e Thiago celebrando a saída da cerimônia"),
    line: "E assim, a história continua",
    lines: ["E assim,", "a história continua"],
  },
} satisfies EditorialCinematicData;
